- hosts: all
  become: yes
  roles:
    - common
    - bench
    - mysql
    - nginx
    - webapp-go
    - webapp-node
    - webapp-perl
    - webapp-php
    - webapp-ruby
    - webapp-python
    - image
